### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by mzfr** [Ashish-012/Dynamic-Blog#1]
Add a detail description of how to setup this and what it exactly is. Maybe add a screenshot

**Comment by Ashish-012** [comment]
I will surely do that once the website is in the testing phase. Thanks for the suggestion.

> Add a detail description of how to setup this and what it exactly is. Maybe add a screenshot

**Comment by mzfr** [comment]
The best thing would be to just add the read to give a breif idea of what exactly the project is about.

And as the project grow keep on updating that readme.

**Comment by Ashish-012** [comment]
> The best thing would be to just add the read to give a breif idea of what exactly the project is about.
> 
> And as the project grow keep on updating that readme.

Readme added. Let me know if anything is missing or needs changes.
