### ISSUE TITLE
Change all the `header(Location: )` to window.location

### ISSUE THREAD

**Issue by Ashish-012** [Ashish-012/Dynamic-Blog#12]
For some reason, while hosting on some online platform the pages are not loading/redirecting correctly. It could be because of the PHP function `header()`. Use javascript `window.location` function instead to fix the issue.

**Comment by mzfr** [comment]
ha ye sahi hai code karna na aye to PHP ki galti nikaal do bhai bhot ache.

bhai Linux pe khud deploy karte to pata hota na dikkat arahi hai magar nahi tum maante kaha ho.

**Comment by Ugtan** [comment]
Mujhe bolte hai bc streak ke liye aase kaam karta hu aur khud wahi karte ho joshi boi, ye sahi nahi hai bhagwaan se toh daro @Ashish-012

**Comment by mzfr** [comment]
> Mujhe bolte hai bc streak ke liye aase kaam karta hu aur khud wahi karte ho joshi boi, ye sahi nahi hai bhagwaan se toh daro @Ashish-012

Usmaan bhai ese gaali mat do bhai magar baat bikul sach hai @Ashish-012 upar vaale se daro

**Comment by Ugtan** [comment]
Ab joshi jinda gali dekar bhagayega.. ki bc bas karo isse acha toh ek commit maar deta tumhe gali deta hua private repo mai jaise mai karta hu(Joking)😂 @Ashish-012

**Comment by mzfr** [comment]
nahi joshi ko pata nahi hai ki ese issues pe conversation lock bhi kar sakte hai

**Comment by Ugtan** [comment]
Hahaha lekin ab koi fyada nahi na.. Damage pehle hi ho chuka hai

**Comment by Ashish-012** [comment]
@mzfr @Ugtan bc github na hua whatsapp hi ho gaya yahi baat karlo saari
