### ISSUE TITLE
Add support for Markdown/HTML Editor

### ISSUE THREAD

**Issue by Ugtan** [Ashish-012/Dynamic-Blog#4]
This might be a challenging task but I'm sure you'll find some libraries that might help you in addition to Markdown/HTML Editor support for your blog app. It will enhance the readability of your blog. It will help the content writer in writing rich formatted content. Hence, it will provide semantic meaning to the blog.

**Comment by Ashish-012** [comment]
An HTML editor `tinymce` has been added. I will update the images soon.
