### ISSUE TITLE
Use of TinyMCE make the pages slow

### ISSUE THREAD

**Issue by mzfr** [Ashish-012/Dynamic-Blog#6]
I noticed that you are using lot of plugins for tinymce and due to that the pages are taking some time to load. Maybe try to remove the unnecessary plugins.

**Comment by Ashish-012** [comment]
Yes, I have noticed that as well. I tried removing some useless plugins still the loading time was a bit much. I may have to remove `TinyMCE` completely. I will update it soon.

**Comment by Ashish-012** [comment]
The page should not take much time to load now.
