### ISSUE TITLE
Allow users to sign up using Google

### ISSUE THREAD

**Issue by Ugtan** [Ashish-012/Dynamic-Blog#8]
There might be folks who don't want to share their password due to security reasons. Also, it is very difficult to remember too many passwords. So, Adding a feature that will allow the users to sign up with the app using their google credentials(Google OAuth 2.0 authentication) will ease the signup process. Also, You can allow the users to sign up via Github, Twitter, etc.

**Comment by mzfr** [comment]
hadd macha rahe ho kuch bhi kuch karoge streak k liye? Streak ka point hi kya hai agar kuch bhi random kaam karna hai ese to purane din k naam se commit karte raho.

Kuch dhang ka karlo usmaan bhai

**Comment by Ugtan** [comment]
Theek hai kal se @mzfr
